import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <div className="w-full flex justify-center items-start overflow-x-hidden">
          <Toaster />
          <AppSidebar>{children}</AppSidebar>
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AppSidebar } from "./components/Sidebar";
// import {
//   SidebarProvider,
//   SidebarInset,
//   SidebarTrigger,
// } from "@/components/ui/sidebar";

// const geistSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// });

// export const metadata: Metadata = {
//   title: "Optimized Next App",
//   description: "An optimized Next.js application with a proper UI structure",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body className="bg-background font-sans antialiased">
//         {/* <SidebarProvider> */}
//         <div className="flex h-screen overflow-hidden">
//           <AppSidebar />
//           <div className="flex flex-col flex-1 overflow-hidden">
//             <header className="flex h-16 items-center gap-4 border-b bg-background px-6">
//               {/* <SidebarTrigger /> */}
//               <div className="font-semibold">Your App Name</div>
//             </header>
//             {/* <SidebarInset> */}
//             <main className="flex-1 overflow-y-auto p-6">{children}</main>
//             <footer className="flex justify-center items-center p-4 border-t bg-background">
//               <p className="text-sm text-muted-foreground">
//                 © {new Date().getFullYear()} Your Company. All rights reserved.
//               </p>
//             </footer>
//             {/* </SidebarInset> */}
//           </div>
//         </div>
//         {/* </SidebarProvider> */}
//       </body>
//     </html>
//   );
// }
